#!/usr/bin/env bash

set -e

repo_dir="$(readlink -f "$(dirname "$0")/..")"
out_dir="$(readlink -f "${repo_dir}/../${PYPI_PATH}/dist")"
mkdir "${out_dir}"

cd $repo_dir

# install build-only dependencies (no need to include in image)
pip3 install --upgrade pip twine wheel setuptools

python3 "${repo_dir}/setup.py" sdist bdist_wheel

model_element_cmd="gardener-ci config model_element --cfg-type pypi --cfg-name gardener"

username="$(${model_element_cmd} --key credentials.username)"
passwd="$(${model_element_cmd} --key credentials.passwd)"


# upload to pypi
twine upload --user "${username}" --password "${passwd}" dist/*
# keep for subsequent docker build
cp dist/* ${out_dir}
